import React,{useState}from"react";import{Pressable,ScrollView,StyleSheet,Text,TextInput,View}from"react-native";import{ScreenContainer}from"@/components/screen-container";import{useColors}from"@/hooks/use-colors";import{useApp}from"@/lib/app-context";import{createLesson}from"@/lib/store";

export default function Cycle(){const c=useColors();const{state,addSubject,updateSubject,deleteSubject,moveSubject}=useApp();const[name,setName]=useState("");const[bulk,setBulk]=useState<Record<string,string>>({});
const add=async()=>{if(name.trim()){await addSubject(name);setName("")}};
const addLessons=async(sid:string)=>{const text=bulk[sid]||"";const titles=text.split(/[\n,;]+/).map(x=>x.trim()).filter(Boolean);const subject=state.cycle.subjects.find(s=>s.id===sid);if(!subject||!titles.length)return;await updateSubject(sid,{lessons:[...subject.lessons,...titles.map(createLesson)]});setBulk(v=>({...v,[sid]:""}))};
return <ScreenContainer containerClassName="bg-background"><ScrollView contentContainerStyle={{padding:20,paddingBottom:40}}>
<Text style={[s.title,{color:c.foreground}]}>Meu ciclo</Text>
<Text style={[s.sub,{color:c.foreground}]}>Defina a ordem, o tempo de cada matéria e depois cadastre as aulas.</Text>
<View style={s.row}><TextInput value={name} onChangeText={setName} placeholder="Nova matéria" placeholderTextColor={c.muted} style={[s.input,{color:c.foreground,borderColor:c.border}]}/><Pressable onPress={add} style={[s.add,{backgroundColor:c.primary}]}><Text style={s.white}>Adicionar</Text></Pressable></View>

{state.cycle.subjects.length>0&&<View style={[s.orderCard,{backgroundColor:c.surface,borderColor:c.border}]}><Text style={[s.section,{color:c.foreground}]}>Ordem do ciclo</Text><Text style={[s.helper,{color:c.foreground}]}>A primeira matéria é a próxima a ser estudada.</Text>{state.cycle.subjects.map((sub,i)=><View key={sub.id} style={[s.orderRow,{borderTopColor:c.border}]}><Text style={[s.number,{color:c.primary}]}>{i+1}</Text><Text style={[s.orderName,{color:c.foreground}]}>{sub.name}</Text><Pressable disabled={i===0} onPress={()=>moveSubject(sub.id,-1)} style={[s.arrow,{borderColor:c.border,opacity:i===0?.35:1}]}><Text style={{color:c.foreground,fontSize:18}}>↑</Text></Pressable><Pressable disabled={i===state.cycle.subjects.length-1} onPress={()=>moveSubject(sub.id,1)} style={[s.arrow,{borderColor:c.border,opacity:i===state.cycle.subjects.length-1?.35:1}]}><Text style={{color:c.foreground,fontSize:18}}>↓</Text></Pressable></View>)}</View>}

{state.cycle.subjects.map((sub,i)=><View key={sub.id} style={[s.card,{backgroundColor:c.surface,borderColor:c.border}]}>
<View style={s.head}><View style={{flex:1}}><Text style={[s.subject,{color:c.foreground}]}>{i+1}. {sub.name}</Text><Text style={[s.smallText,{color:c.foreground}]}>{sub.lessons.filter(l=>l.status==="concluida").length}/{sub.lessons.length} aulas concluídas</Text></View><Pressable onPress={()=>deleteSubject(sub.id)} hitSlop={10}><Text style={{color:c.error,fontWeight:"700"}}>Excluir</Text></Pressable></View>
<Text style={[s.label,{color:c.foreground}]}>Horas por semana</Text><TextInput value={sub.weeklyHours?String(sub.weeklyHours):""} onChangeText={v=>updateSubject(sub.id,{weeklyHours:Math.max(0,Number(v.replace(",","."))||0)})} keyboardType="decimal-pad" placeholder="Ex.: 6" placeholderTextColor={c.muted} style={[s.input,{color:c.foreground,borderColor:c.border}]}/>
<Text style={[s.label,{color:c.foreground}]}>Adicionar várias aulas</Text><TextInput value={bulk[sub.id]||""} onChangeText={v=>setBulk(x=>({...x,[sub.id]:v}))} placeholder="Uma aula por linha (ou separada por vírgula)" placeholderTextColor={c.muted} multiline style={[s.bulk,{color:c.foreground,borderColor:c.border}]}/>
<Pressable onPress={()=>addLessons(sub.id)} style={[s.small,{borderColor:c.primary,backgroundColor:c.primary+"12"}]}><Text style={{color:c.primary,fontWeight:"800"}}>Adicionar aulas</Text></Pressable>
<Text style={[s.label,{color:c.foreground}]}>Anotações da matéria</Text><TextInput value={sub.notes} onChangeText={v=>updateSubject(sub.id,{notes:v})} placeholder="Anote o que precisa lembrar..." placeholderTextColor={c.muted} multiline style={[s.bulk,{color:c.foreground,borderColor:c.border}]}/>
{sub.lessons.map(l=><View key={l.id} style={[s.lesson,{borderTopColor:c.border}]}><Text style={{color:c.foreground,flex:1,fontSize:15,fontWeight:"600"}}>{l.title}</Text><Text style={{color:l.status==="concluida"?c.success:c.foreground,fontWeight:"700"}}>{l.status==="concluida"?"Concluída":l.status==="continuar"?"Continuar":"Pendente"}</Text></View>)}
</View>)}
{!state.cycle.subjects.length&&<View style={[s.empty,{borderColor:c.border}]}><Text style={[s.emptyTitle,{color:c.foreground}]}>Seu ciclo está vazio</Text><Text style={[s.helper,{color:c.foreground}]}>Adicione as matérias acima para começar.</Text></View>}
</ScrollView></ScreenContainer>}

const s=StyleSheet.create({title:{fontSize:30,fontWeight:"900"},sub:{fontSize:15,lineHeight:22,marginTop:7,marginBottom:18},row:{flexDirection:"row",gap:8},input:{borderWidth:1.5,borderRadius:10,padding:12,fontSize:16,flex:1,backgroundColor:"transparent"},add:{borderRadius:10,paddingHorizontal:16,justifyContent:"center"},white:{color:"#fff",fontWeight:"800"},orderCard:{borderWidth:1.5,borderRadius:16,padding:16,marginTop:18},section:{fontSize:18,fontWeight:"900"},helper:{fontSize:14,lineHeight:20,marginTop:4},orderRow:{flexDirection:"row",alignItems:"center",paddingVertical:10,borderTopWidth:1,marginTop:8},number:{fontSize:18,fontWeight:"900",width:28},orderName:{flex:1,fontSize:15,fontWeight:"700"},arrow:{width:36,height:36,borderWidth:1.5,borderRadius:9,alignItems:"center",justifyContent:"center",marginLeft:6},card:{borderWidth:1.5,borderRadius:16,padding:16,marginTop:14},head:{flexDirection:"row",alignItems:"center"},subject:{fontSize:19,fontWeight:"900"},smallText:{fontSize:13,marginTop:3},label:{fontSize:14,fontWeight:"800",marginTop:14,marginBottom:6},bulk:{borderWidth:1.5,borderRadius:10,padding:12,minHeight:82,textAlignVertical:"top",fontSize:15},small:{borderWidth:1.5,borderRadius:10,padding:12,alignItems:"center",marginTop:8},lesson:{flexDirection:"row",paddingVertical:11,borderTopWidth:1,marginTop:8,gap:10},empty:{borderWidth:1.5,borderRadius:16,padding:24,marginTop:18},emptyTitle:{fontSize:18,fontWeight:"900"}});